[project]
name = "ls2_overview"
version = "0.1.0"
description = "Simple tools for early visualization of LS2 experiments."
requires-python = ">=3.11"
dependencies = [
    "click>=8.1",
    "polars",
]

[project.scripts]
delete_empty_tifs = "ls2_overview.delete_empty_tifs:cli"

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/ls2_overview"]